### ISSUE TITLE
Script not working after upgrading to 2023.4.3

### ISSUE THREAD

**Issue by kaizersoje** [apop880/config-check#19]
After upgrading to HA OS Core 2023.4.3, I have noticed that running `script.check_config` does nothing. The state of `sensor.config_result` remains as `-`; it does not change at all.

**Comment by posreg** [comment]
the same for me

addon logs:

```
2023-04-17 13:57:42.750423 WARNING check_config: ------------------------------------------------------------
2023-04-17 13:57:42.752168 WARNING check_config: Unexpected error running initialize() for check_config
2023-04-17 13:57:42.753788 WARNING check_config: ------------------------------------------------------------
2023-04-17 13:57:42.761951 WARNING check_config: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/check-config/checkconfig.py", line 28, in initialize
    self.apiurl = "{}/api/config/core/check_config".format(self.config["plugins"]["HASS"]["ha_url"])
KeyError: 'ha_url'
```

**Comment by DavidFW1960** [comment]
same in 2023.5.0bx
stopped working now

**Comment by posreg** [comment]
any chances for the fix please ?
Does anybody know other solution/workaround ?

**Comment by leprechaun17** [comment]
Need to specify HA_URL in your appdaemon.yaml file. Looks like this:
  plugins:
    HASS:
      type: hass
      ha_url: http://XXX.XXX.XX.XX:8123
      token: (create a long live token in Homeassistant and paste it here)
