### ISSUE TITLE
Not working in Appdaemon 4.X

### ISSUE THREAD

**Issue by kflinderman** [apop880/config-check#6]
I just figured I would try updating to the Appdaemon V4.0 add-on and I got this error when starting.
```
2020-01-14 17:54:45.582743 WARNING check_config: ------------------------------------------------------------
2020-01-14 17:54:45.583961 WARNING check_config: Unexpected error running initialize() for check_config
2020-01-14 17:54:45.585291 WARNING check_config: ------------------------------------------------------------
2020-01-14 17:54:45.603227 WARNING check_config: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/check-config/checkconfig.py", line 25, in initialize
    self.set_state("sensor.config_result", state="-", attributes = {"friendly_name": "Config Result", "detail": None})
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 285, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 1360, in set_state
    return await self.AD.state.set_state(self.name, namespace, entity_id, **kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/state.py", line 431, in set_state
    result = await plugin.set_plugin_state(namespace, entity_id, **kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/plugins/hass/hassplugin.py", line 369, in set_plugin_state
    api_url = "{}/api/states/{}".format(config["ha_url"], entity_id)
KeyError: 'ha_url'
```

**Comment by DavidFW1960** [comment]
Same here
```
2020-01-15 10:37:53.551616 WARNING check_config: ------------------------------------------------------------
2020-01-15 10:37:53.551987 WARNING check_config: Unexpected error running initialize() for check_config
2020-01-15 10:37:53.552299 WARNING check_config: ------------------------------------------------------------
2020-01-15 10:37:53.556375 WARNING check_config: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/check-config/checkconfig.py", line 25, in initialize
    self.set_state("sensor.config_result", state="-", attributes = {"friendly_name": "Config Result", "detail": None})
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 285, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 1360, in set_state
    return await self.AD.state.set_state(self.name, namespace, entity_id, **kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/state.py", line 431, in set_state
    result = await plugin.set_plugin_state(namespace, entity_id, **kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/plugins/hass/hassplugin.py", line 369, in set_plugin_state
    api_url = "{}/api/states/{}".format(config["ha_url"], entity_id)
KeyError: 'ha_url'

2020-01-15 10:37:53.556654 WARNING check_config: ------------------------------------------------------------
2020-01-15 10:37:53.557812 INFO AppDaemon: App initialization complete
```

**Comment by DavidFW1960** [comment]
So Frenck just released an updated Appdaemon 4 (0.1.1) and now check_config is working again.

**Comment by DavidFW1960** [comment]
I had to reload scripts to make it run though... My check button isn't triggering it.

**Comment by kflinderman** [comment]
After reloading scripts and everything I'm actually right there with you. I forgot to check to see if it were working or not. Nothing seems to happen when I execute the script.

**Comment by bussio** [comment]
When I press the "Execute" button, I can see no reaction. The entity sensor.config.result contains nothing as value.

2020-01-16 15:08:43.303210 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:08:48.313630 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:08:48.320914 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:08:53.329559 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:08:53.335401 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:08:58.346756 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:08:58.353629 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:09:03.363514 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:09:03.375361 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:09:08.385095 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:09:08.394696 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:09:13.403325 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:09:13.411195 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:09:18.418809 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:09:18.424988 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:09:23.433183 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:09:23.439442 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:09:28.449326 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:09:28.456114 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:09:33.466232 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:09:35.174925 INFO HASS: Evaluating startup conditions
2020-01-16 15:09:35.292634 INFO AppDaemon: Processing restart for HASS
2020-01-16 15:09:35.294160 INFO AppDaemon: Terminating hello_world
2020-01-16 15:09:35.295952 INFO AppDaemon: Terminating check_config
2020-01-16 15:09:35.297892 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2020-01-16 15:09:35.301668 INFO AppDaemon: Initializing app check_config using class CheckConfig from module checkconfig
2020-01-16 15:09:35.309006 INFO hello_world: Hello from AppDaemon
2020-01-16 15:09:35.310744 INFO hello_world: You are now ready to run Apps!
2020-01-16 15:09:35.315697 WARNING check_config: check_config: Entity sensor.config_result not found in namespace default
2020-01-16 15:09:35.317308 INFO AppDaemon: check_config: Entity sensor.config_result created in namespace: default
2020-01-16 15:16:22.856412 WARNING check_config: ------------------------------------------------------------
2020-01-16 15:16:22.858209 WARNING check_config: Unexpected error in worker for App check_config:
2020-01-16 15:16:22.859470 WARNING check_config: Worker Ags: {'id': '31ffd11be8aa4864b48428ea5f77b5f3', 'name': 'check_config', 'objectid': 'ce12c1321e244ac7b74ca28b45e9e438', 'type': 'state', 'function': <bound method CheckConfig.check_config of <checkconfig.CheckConfig object at 0x7f7b20d1bf40>>, 'attribute': 'state', 'entity': 'script.check_config', 'new_state': None, 'old_state': 'off', 'pin_app': True, 'pin_thread': 1, 'kwargs': {'__thread_id': 'thread-1'}}
2020-01-16 15:16:22.860787 WARNING check_config: ------------------------------------------------------------
2020-01-16 15:16:22.908656 WARNING check_config: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 777, in worker
    funcref(entity, attr, old_state, new_state,
  File "/config/appdaemon/apps/check-config/checkconfig.py", line 62, in check_config
    self.call_service("homeassistant/restart")
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 285, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 441, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

2020-01-16 15:16:22.909175 WARNING check_config: ------------------------------------------------------------
2020-01-16 15:16:22.911210 WARNING AppDaemon: callback check_config() in check_config has now completed
2020-01-16 15:16:57.994494 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:16:58.171683 WARNING HASS: Attempt to call Home Assistant while disconnected: set_plugin_state
2020-01-16 15:16:58.174114 WARNING HASS: Attempt to call Home Assistant while disconnected: call_plugin_service
2020-01-16 15:16:58.177054 WARNING AppDaemon: callback check_config() in check_config has now completed
2020-01-16 15:17:03.002077 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:17:03.008168 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:17:08.016583 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:17:08.023494 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:17:13.034267 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:17:13.041747 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:17:18.050765 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:17:18.059268 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:17:23.067786 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:17:23.074618 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:17:28.083880 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:17:28.092748 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:17:33.101683 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:17:33.110239 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:17:38.120977 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:17:38.131230 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:17:43.140457 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:17:43.149808 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:17:48.162281 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:17:48.169454 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:17:53.177464 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:17:53.183445 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:17:58.191644 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:17:58.197567 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:18:03.205819 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:18:03.212071 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:18:08.221123 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:18:08.227484 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:18:13.236395 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:18:13.242439 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:18:18.252329 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:18:18.260111 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:18:23.268701 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:18:23.274873 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:18:28.288012 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:18:28.294175 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2020-01-16 15:18:33.303970 INFO HASS: Connected to Home Assistant 0.104.0
2020-01-16 15:18:34.200096 INFO HASS: Evaluating startup conditions
2020-01-16 15:18:34.346946 INFO AppDaemon: Processing restart for HASS
2020-01-16 15:18:34.348396 INFO AppDaemon: Terminating hello_world
2020-01-16 15:18:34.353504 INFO AppDaemon: Terminating check_config
2020-01-16 15:18:34.355759 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2020-01-16 15:18:34.360827 INFO AppDaemon: Initializing app check_config using class CheckConfig from module checkconfig
2020-01-16 15:18:34.366205 INFO hello_world: Hello from AppDaemon
2020-01-16 15:18:34.369336 INFO hello_world: You are now ready to run Apps!
2020-01-16 15:18:34.379088 WARNING check_config: check_config: Entity sensor.config_result not found in namespace default
2020-01-16 15:18:34.380582 INFO AppDaemon: check_config: Entity sensor.config_result created in namespace: default

**Comment by apop880** [comment]
This should be fixed as of version 0.3.1. Please retest, I'll leave this open until I have confirmation that it's working for others.

**Comment by DavidFW1960** [comment]
Confirmed working here. Thanks.

**Comment by apop880** [comment]
Thanks! I totally missed that it was you on here and on the forum thread. I'll get this closed out then!

**Comment by bussio** [comment]
Confirmed working here. Thanks.
